### ISSUE TITLE
[BUG] total_results ne donne pas la bonne valeur

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/annuaire-entreprises-search-api#150]
## Sujet du problème
La valeur de `total_results` ne correspond pas au nombre d'éléments dans `results`

## Comment le reproduire ?
1. Effectuer la requête https://recherche-entreprises.api.gouv.fr/search?q=420495178
2. Constater que `results` ne comporte qu'un élément alors que `total_results` vaut `2`

## Comportement attendu
`total_results` comprend le nombre d'éléments dans `results`

**Comment by geoffreyaldebert** [comment]
Salut @AntoineAugusti ! Ravi de te retrouver ici ;)

Alors l'explication : 

Pour une raison de performance, on a du "splitter" certaines entreprises volumineuses (les entreprises qui possèdent plus de 100 établissements) en plusieurs documents elasticsearch. C'est le cas de celle que tu pointe qui a 171 établissements. Au moment de la requête elasticsearch, on fait un `collapse` des résultats pour ne pas doublonner les résultats. C'est pour cela qu'on affiche qu'un document mais que dans les faits il y a deux documents elasticsearch qui correspondent. Le cas extrême étant celui de [La Poste](https://recherche-entreprises.api.gouv.fr/search?q=356000000) qui renvoit un document pour 128 résultats annoncés (la poste à ~10k établissements).

On a mis en prod cette feature hier (et comme d'habitude tu m'impressionnes par ta capacité à détecter un changement sur les produits) donc on va regarder comment traiter le problème, merci du signalement. Ce n'est peut-être pas évident de le faire depuis elasticsearch mais on devrait trouver une parade pour gérer ce type de cas.

@HAEKADI va te tenir informer de l'avancement sur cette issue

**Comment by AntoineAugusti** [comment]
@geoffreyaldebert Ahah, j'ai uniquement de la chance sur cette fois !

Je travaillais sur https://github.com/etalab/transport-site/pull/2953 ce matin, "Air France" (SIREN 420495178) est un cas de test pertinent pour transport.data.gouv.fr donc je suis tombé dessus complétement par hasard 😂

**Comment by AntoineAugusti** [comment]
Merci pour le fix express @HAEKADI !
