### ISSUE TITLE
[Labels et certificats] Ajout du `statut_organisme_formation`

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-search-api#227]
https://support.etalab.gouv.fr/#ticket/zoom/57807

Remontée d'utilisateurs : comme pour le spectacle vivant, il faut distinguer les entreprises certifiées de celles qui n'ont pas de certificat en cours de validité

Ce champs peut etre placé dans `complements` au niveau du siren

**Comment by HAEKADI** [comment]
Nous avons fini par filtrer les entreprises qui n'ont pas de certifications comme `non qualiopi` même si celles-ci figurent sur le fichier d'organismes de formation.
