### ISSUE TITLE
[Labels & certificats] Marché de l'Inclusion

### ISSUE THREAD

**Issue by XavierJp** [etalab/annuaire-entreprises-search-api#304]
côté Marché de l’Inclusion :
- ajouter les parents dans la payload
- mettre un mtm_campaign dans le lien vers l’annuaire pour mesurer l’engagement des utilisateurs
- nous générer un token pour l’API

côté Annuaire :
- on se base plutot sur les parents que les kinds dans le résumé de la page entreprise
- on utilise le token et on ajoute les parents dans la recherche entreprise
  - route a utiliser https://lemarche.inclusion.beta.gouv.fr/api/siae
  - si une entreprise est dans la liste mais pas chez ESS France, warning à remonter
- on utilise l’API (route siret) dans la page labels & certificats 
  - Ex : https://lemarche.inclusion.beta.gouv.fr/api/siae/siret/87833593400013/
  - on construit le lien vers la page du Marché de l’Inclusion grâce au slug
  - on ajoute un mtm_campaign
- NB : mieux vaut ignorer les services emploi pénitentiaires
  - https://lemarche.inclusion.beta.gouv.fr/api/siae/siret/41827166400066/

**Comment by HAEKADI** [comment]
Proposition d'insertion :
* Au niveau de l'unité légale : rajouter un booléen `est_inclusive` (ou `est_siae`) si l'UL détient minimum un siret siae
* Au niveau de l'établissement : rajouer un champ `type_siae`(handicap ou insertion)
* Rajouter un filtre `est_siae`

Tu en penses-quoi @XavierJp ?

**Comment by XavierJp** [comment]
```
// filter
est_siae

// unite legale
complements: {
  est_siae: true|false,
  type_siae: [] 
}
```
