### ISSUE TITLE
[Siège] : Ajouter la données `annee_tranche_effectif_salarié`

### ISSUE THREAD

**Issue by johangirod** [etalab/annuaire-entreprises-search-api#310]
Cette donnée est retournée par l'API insee pour le siège et elle manque pour se passer des appels insee.

Cf https://github.com/etalab/annuaire-entreprises-site/pull/767

Ce n'est pas forcément critique, mais c'est une petite regression.

**Comment by HAEKADI** [comment]
Tu parles bien de `annee_tranche_effectif_salarie` ?
Elle est inclue dans la réponse normalement.

**Comment by HAEKADI** [comment]
Ok, et vous en avez besoin pour le siège uniquement ou pour les établissements secondaires également ?

**Comment by johangirod** [comment]
1. Pour éviter la regression, uniquement sur le siège.
2. Si on souhaite corriger un petit bug sur l'affichage des page établissement, ça peut être chouette de le rajouter sur les établissement secondaire dans un second temps (exemple : https://annuaire-entreprises.data.gouv.fr/entreprise/danone-552032534)
